# ---------------------------------------------------------------------------
# Comprehensive Indian Stock Market Database (NSE)
# Maps company names to Yahoo Finance tickers (.NS suffix)
# ---------------------------------------------------------------------------

STOCKS = {
    # ── NIFTY 50 ──────────────────────────────────────────────────────────
    "Reliance Industries": "RELIANCE.NS",
    "Tata Consultancy Services": "TCS.NS",
    "Infosys": "INFY.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "State Bank of India": "SBIN.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "Hindustan Unilever": "HINDUNILVR.NS",
    "ITC": "ITC.NS",
    "Kotak Mahindra Bank": "KOTAKBANK.NS",
    "Larsen & Toubro": "LT.NS",
    "Axis Bank": "AXISBANK.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "Bajaj Finserv": "BAJAJFINSV.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "HCL Technologies": "HCLTECH.NS",
    "Titan Company": "TITAN.NS",
    "Sun Pharmaceutical": "SUNPHARMA.NS",
    "Wipro": "WIPRO.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "NTPC": "NTPC.NS",
    "Power Grid Corporation": "POWERGRID.NS",
    "UltraTech Cement": "ULTRACEMCO.NS",
    "Nestle India": "NESTLEIND.NS",
    "IndusInd Bank": "INDUSINDBK.NS",
    "Adani Enterprises": "ADANIENT.NS",
    "Adani Ports": "ADANIPORTS.NS",
    "Tech Mahindra": "TECHM.NS",
    "Mahindra & Mahindra": "M&M.NS",
    "Tata Steel": "TATASTEEL.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "Hindalco Industries": "HINDALCO.NS",
    "Grasim Industries": "GRASIM.NS",
    "Oil & Natural Gas Corporation": "ONGC.NS",
    "Coal India": "COALINDIA.NS",
    "Cipla": "CIPLA.NS",
    "Dr Reddys Laboratories": "DRREDDY.NS",
    "Eicher Motors": "EICHERMOT.NS",
    "Hero MotoCorp": "HEROMOTOCO.NS",
    "Divis Laboratories": "DIVISLAB.NS",
    "Britannia Industries": "BRITANNIA.NS",
    "Apollo Hospitals": "APOLLOHOSP.NS",
    "SBI Life Insurance": "SBILIFE.NS",
    "HDFC Life Insurance": "HDFCLIFE.NS",
    "Bajaj Auto": "BAJAJ-AUTO.NS",
    "Tata Consumer Products": "TATACONSUM.NS",
    "Bharat Petroleum": "BPCL.NS",
    "Hindustan Petroleum": "HINDPETRO.NS",
    "Indian Oil Corporation": "IOC.NS",

    # ── NIFTY NEXT 50 / MID-CAPS ─────────────────────────────────────────
    "Vedanta": "VEDL.NS",
    "Ambuja Cements": "AMBUJACEM.NS",
    "ACC": "ACC.NS",
    "Godrej Consumer Products": "GODREJCP.NS",
    "Godrej Properties": "GODREJPROP.NS",
    "Pidilite Industries": "PIDILITIND.NS",
    "Havells India": "HAVELLS.NS",
    "Siemens": "SIEMENS.NS",
    "ABB India": "ABB.NS",
    "Bosch": "BOSCH.NS",
    "DLF": "DLF.NS",
    "Shree Cement": "SHREECEM.NS",
    "Dalmia Bharat": "DALBHARAT.NS",
    "Berger Paints": "BERGEPAINT.NS",
    "Info Edge (Naukri)": "NAUKRI.NS",
    "Muthoot Finance": "MUTHOOTFIN.NS",
    "Bandhan Bank": "BANDHANBNK.NS",
    "IDFC First Bank": "IDFCFIRSTB.NS",
    "Federal Bank": "FEDERALBNK.NS",
    "AU Small Finance Bank": "AUBANK.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "Punjab National Bank": "PNB.NS",
    "Canara Bank": "CANBK.NS",
    "Indian Bank": "INDIANB.NS",
    "Union Bank of India": "UNIONBANK.NS",
    "IDBI Bank": "IDBI.NS",
    "Yes Bank": "YESBANK.NS",
    "RBL Bank": "RBLBANK.NS",
    "Cholamandalam Investment": "CHOLAFIN.NS",
    "Shriram Finance": "SHRIRAMFIN.NS",
    "Manappuram Finance": "MANAPPURAM.NS",
    "LIC Housing Finance": "LICHSGFIN.NS",
    "SBI Cards": "SBICARD.NS",
    "ICICI Lombard": "ICICIGI.NS",
    "ICICI Prudential Life": "ICICIPRULI.NS",
    "General Insurance Corporation": "GICRE.NS",
    "New India Assurance": "NIACL.NS",

    # ── IT / TECH ─────────────────────────────────────────────────────────
    "Mphasis": "MPHASIS.NS",
    "L&T Technology Services": "LTTS.NS",
    "L&T Infotech (LTIMindtree)": "LTIM.NS",
    "Persistent Systems": "PERSISTENT.NS",
    "Coforge": "COFORGE.NS",
    "Happiest Minds": "HAPPSTMNDS.NS",
    "Zensar Technologies": "ZENSARTECH.NS",
    "KPIT Technologies": "KPITTECH.NS",
    "Tata Elxsi": "TATAELXSI.NS",
    "Cyient": "CYIENT.NS",
    "Oracle Financial Services": "OFSS.NS",

    # ── PHARMA / HEALTHCARE ───────────────────────────────────────────────
    "Lupin": "LUPIN.NS",
    "Aurobindo Pharma": "AUROPHARMA.NS",
    "Torrent Pharmaceuticals": "TORNTPHARM.NS",
    "Alkem Laboratories": "ALKEM.NS",
    "Biocon": "BIOCON.NS",
    "Laurus Labs": "LAURUSLABS.NS",
    "Glenmark Pharmaceuticals": "GLENMARK.NS",
    "Ipca Laboratories": "IPCALAB.NS",
    "Max Healthcare": "MAXHEALTH.NS",
    "Fortis Healthcare": "FORTIS.NS",
    "Narayana Hrudayalaya": "NH.NS",
    "Metropolis Healthcare": "METROPOLIS.NS",
    "Dr Lal PathLabs": "LALPATHLAB.NS",

    # ── AUTO / AUTO ANCILLARY ─────────────────────────────────────────────
    "Tata Motors DVR": "TATAMTRDVR.NS",
    "Ashok Leyland": "ASHOKLEY.NS",
    "TVS Motor Company": "TVSMOTOR.NS",
    "Motherson Sumi": "MOTHERSON.NS",
    "MRF": "MRF.NS",
    "Apollo Tyres": "APOLLOTYRE.NS",
    "Bharat Forge": "BHARATFORG.NS",
    "Escorts Kubota": "ESCORTS.NS",
    "Tube Investments": "TIINDIA.NS",
    "Sona BLW Precision": "SONACOMS.NS",

    # ── FMCG / CONSUMER ──────────────────────────────────────────────────
    "Dabur India": "DABUR.NS",
    "Marico": "MARICO.NS",
    "Colgate-Palmolive India": "COLPAL.NS",
    "Emami": "EMAMI.NS",
    "Tata Consumer Products": "TATACONSUM.NS",
    "United Spirits": "UNITDSPR.NS",
    "United Breweries": "UBL.NS",
    "Varun Beverages": "VBL.NS",
    "Jubilant FoodWorks": "JUBLFOOD.NS",

    # ── ENERGY / POWER / UTILITIES ────────────────────────────────────────
    "Adani Green Energy": "ADANIGREEN.NS",
    "Adani Total Gas": "ATGL.NS",
    "Adani Power": "ADANIPOWER.NS",
    "Adani Wilmar": "AWL.NS",
    "Tata Power": "TATAPOWER.NS",
    "JSW Energy": "JSWENERGY.NS",
    "NHPC": "NHPC.NS",
    "SJVN": "SJVN.NS",
    "Torrent Power": "TORNTPOWER.NS",
    "Inox Wind": "INOXWIND.NS",
    "GAIL India": "GAIL.NS",
    "Petronet LNG": "PETRONET.NS",
    "Gujarat Gas": "GUJGASLTD.NS",
    "Indraprastha Gas": "IGL.NS",
    "Mahanagar Gas": "MGL.NS",

    # ── METALS / MINING ───────────────────────────────────────────────────
    "Tata Steel Long Products": "TATASTLLP.NS",
    "Jindal Steel & Power": "JINDALSTEL.NS",
    "Steel Authority of India": "SAIL.NS",
    "NMDC": "NMDC.NS",
    "National Aluminium": "NATIONALUM.NS",
    "Hindustan Zinc": "HINDZINC.NS",
    "Hindustan Copper": "HINDCOPPER.NS",

    # ── INFRASTRUCTURE / CONSTRUCTION ─────────────────────────────────────
    "Adani Enterprises": "ADANIENT.NS",
    "IRB Infrastructure": "IRB.NS",
    "NCC": "NCC.NS",
    "KNR Constructions": "KNRCON.NS",
    "Oberoi Realty": "OBEROIRLTY.NS",
    "Brigade Enterprises": "BRIGADE.NS",
    "Prestige Estates": "PRESTIGE.NS",
    "Phoenix Mills": "PHOENIXLTD.NS",
    "Sobha": "SOBHA.NS",
    "Macrotech Developers (Lodha)": "LODHA.NS",

    # ── TELECOM / MEDIA ───────────────────────────────────────────────────
    "Vodafone Idea": "IDEA.NS",
    "Indus Towers": "INDUSTOWER.NS",
    "Zee Entertainment": "ZEEL.NS",
    "PVR INOX": "PVRINOX.NS",
    "Sun TV Network": "SUNTV.NS",

    # ── CHEMICALS / SPECIALITY ────────────────────────────────────────────
    "SRF": "SRF.NS",
    "Aarti Industries": "AARTIIND.NS",
    "Deepak Nitrite": "DEEPAKNTR.NS",
    "Navin Fluorine": "NAVINFLUOR.NS",
    "PI Industries": "PIIND.NS",
    "UPL": "UPL.NS",
    "Tata Chemicals": "TATACHEM.NS",
    "Atul": "ATUL.NS",

    # ── DEFENCE / PSU ─────────────────────────────────────────────────────
    "Hindustan Aeronautics": "HAL.NS",
    "Bharat Electronics": "BEL.NS",
    "Bharat Dynamics": "BDL.NS",
    "Mazagon Dock Shipbuilders": "MAZDOCK.NS",
    "Cochin Shipyard": "COCHINSHIP.NS",
    "Garden Reach Shipbuilders": "GRSE.NS",
    "BEML": "BEML.NS",
    "IRCTC": "IRCTC.NS",
    "Indian Railway Finance Corp": "IRFC.NS",
    "Rail Vikas Nigam": "RVNL.NS",

    # ── NEW AGE / TECH STOCKS ─────────────────────────────────────────────
    "Zomato": "ZOMATO.NS",
    "Paytm (One97 Communications)": "PAYTM.NS",
    "Nykaa (FSN E-Commerce)": "NYKAA.NS",
    "PB Fintech (PolicyBazaar)": "POLICYBZR.NS",
    "Delhivery": "DELHIVERY.NS",
    "CarTrade Tech": "CARTRADE.NS",
    "Nazara Technologies": "NAZARA.NS",
    "MapMyIndia (CE Info Systems)": "MAPMYINDIA.NS",
    "Easy Trip Planners": "EASEMYTRIP.NS",
    "FirstCry (Brainbees Solutions)": "FIRSTCRY.NS",
    "Ola Electric": "OLAELEC.NS",
    "Swiggy": "SWIGGY.NS",

    # ── DIVERSIFIED / CONGLOMERATE ────────────────────────────────────────
    "ITC": "ITC.NS",
    "Tata Investment Corporation": "TATAINVSTL.NS",
    "Aditya Birla Capital": "ABCAPITAL.NS",
    "Aditya Birla Fashion": "ABFRL.NS",
    "Max Financial Services": "MFSL.NS",
    "Piramal Enterprises": "PEL.NS",
    "Trent": "TRENT.NS",
    "Voltas": "VOLTAS.NS",
    "Crompton Greaves Consumer": "CROMPTON.NS",
    "Whirlpool of India": "WHIRLPOOL.NS",
    "Dixon Technologies": "DIXON.NS",
    "Kaynes Technology": "KAYNES.NS",

    # ── CEMENT ────────────────────────────────────────────────────────────
    "Ramco Cements": "RAMCOCEM.NS",
    "JK Cement": "JKCEMENT.NS",
    "India Cements": "INDIACEM.NS",
    "Star Cement": "STARCEMENT.NS",

    # ── INSURANCE ─────────────────────────────────────────────────────────
    "Life Insurance Corporation": "LICI.NS",
    "Star Health Insurance": "STARHEALTH.NS",

    # ── MISCELLANEOUS ─────────────────────────────────────────────────────
    "Indian Energy Exchange": "IEX.NS",
    "BSE Ltd": "BSE.NS",
    "Multi Commodity Exchange": "MCX.NS",
    "CAMS": "CAMS.NS",
    "Angel One": "ANGELONE.NS",
    "5Paisa Capital": "5PAISA.NS",
    "Motilal Oswal Financial": "MOTILALOFS.NS",
    "IIFL Finance": "IIFL.NS",
    "Page Industries": "PAGEIND.NS",
    "Relaxo Footwears": "RELAXO.NS",
    "Bata India": "BATAINDIA.NS",
    "Avenue Supermarts (DMart)": "DMART.NS",
    "Tata Communications": "TATACOMM.NS",
    "InterGlobe Aviation (IndiGo)": "INDIGO.NS",
    "SpiceJet": "SPICEJET.NS",
}

# ---------------------------------------------------------------------------
# INDEX FUNDS – used for the ticker tape on the front page
# ---------------------------------------------------------------------------
INDEX_FUNDS = {
    "NIFTY 50": "^NSEI",
    "SENSEX": "^BSESN",
    "NIFTY BANK": "^NSEBANK",
    "NIFTY IT": "^CNXIT",
    "NIFTY NEXT 50": "^NSMIDCP",
    "INDIA VIX": "^INDIAVIX",
}

# ---------------------------------------------------------------------------
# Common aliases / abbreviations → canonical company name
# ---------------------------------------------------------------------------
ALIASES = {
    # Ticker shortcuts
    "tcs": "Tata Consultancy Services",
    "infy": "Infosys",
    "sbi": "State Bank of India",
    "sbin": "State Bank of India",
    "ril": "Reliance Industries",
    "reliance": "Reliance Industries",
    "hul": "Hindustan Unilever",
    "hdfc": "HDFC Bank",
    "icici": "ICICI Bank",
    "kotak": "Kotak Mahindra Bank",
    "lt": "Larsen & Toubro",
    "l&t": "Larsen & Toubro",
    "bpcl": "Bharat Petroleum",
    "hpcl": "Hindustan Petroleum",
    "ioc": "Indian Oil Corporation",
    "ongc": "Oil & Natural Gas Corporation",
    "ntpc": "NTPC",
    "nhpc": "NHPC",
    "hal": "Hindustan Aeronautics",
    "bel": "Bharat Electronics",
    "irctc": "IRCTC",
    "irfc": "Indian Railway Finance Corp",
    "rvnl": "Rail Vikas Nigam",
    "techm": "Tech Mahindra",
    "hcltech": "HCL Technologies",
    "wipro": "Wipro",
    "maruti": "Maruti Suzuki",
    "tatamotors": "Tata Motors",
    "tata motors": "Tata Motors",
    "tata steel": "Tata Steel",
    "tata power": "Tata Power",
    "bajaj finance": "Bajaj Finance",
    "bajaj finserv": "Bajaj Finserv",
    "bajaj auto": "Bajaj Auto",
    "bajaj": "Bajaj Finance",
    "titan": "Titan Company",
    "asian paints": "Asian Paints",
    "asianpaint": "Asian Paints",
    "sunpharma": "Sun Pharmaceutical",
    "sun pharma": "Sun Pharmaceutical",
    "cipla": "Cipla",
    "drreddy": "Dr Reddys Laboratories",
    "dr reddy": "Dr Reddys Laboratories",
    "lupin": "Lupin",
    "biocon": "Biocon",
    "ultratech": "UltraTech Cement",
    "dlf": "DLF",
    "coal india": "Coal India",
    "coalindia": "Coal India",
    "adani": "Adani Enterprises",
    "zomato": "Zomato",
    "paytm": "Paytm (One97 Communications)",
    "nykaa": "Nykaa (FSN E-Commerce)",
    "policybazaar": "PB Fintech (PolicyBazaar)",
    "delhivery": "Delhivery",
    "dmart": "Avenue Supermarts (DMart)",
    "indigo": "InterGlobe Aviation (IndiGo)",
    "spicejet": "SpiceJet",
    "airtel": "Bharti Airtel",
    "jio": "Reliance Industries",
    "vodafone": "Vodafone Idea",
    "vi": "Vodafone Idea",
    "idea": "Vodafone Idea",
    "vedanta": "Vedanta",
    "pnb": "Punjab National Bank",
    "bob": "Bank of Baroda",
    "canara": "Canara Bank",
    "idbi": "IDBI Bank",
    "yes bank": "Yes Bank",
    "yesbank": "Yes Bank",
    "sail": "Steel Authority of India",
    "nmdc": "NMDC",
    "jsw steel": "JSW Steel",
    "jsw energy": "JSW Energy",
    "hindalco": "Hindalco Industries",
    "gail": "GAIL India",
    "igl": "Indraprastha Gas",
    "mgl": "Mahanagar Gas",
    "pidilite": "Pidilite Industries",
    "havells": "Havells India",
    "voltas": "Voltas",
    "crompton": "Crompton Greaves Consumer",
    "dixon": "Dixon Technologies",
    "naukri": "Info Edge (Naukri)",
    "mapmyindia": "MapMyIndia (CE Info Systems)",
    "easemytrip": "Easy Trip Planners",
    "angel one": "Angel One",
    "angel": "Angel One",
    "bse": "BSE Ltd",
    "mcx": "Multi Commodity Exchange",
    "lici": "Life Insurance Corporation",
    "lic": "Life Insurance Corporation",
    "srf": "SRF",
    "upl": "UPL",
    "mrf": "MRF",
    "page": "Page Industries",
    "bata": "Bata India",
    "trent": "Trent",
    "lodha": "Macrotech Developers (Lodha)",
    "oberoi": "Oberoi Realty",
    "prestige": "Prestige Estates",
    "brigade": "Brigade Enterprises",
    "sobha": "Sobha",
    "firstcry": "FirstCry (Brainbees Solutions)",
    "swiggy": "Swiggy",
    "ola": "Ola Electric",
    "itc": "ITC",
    "zee": "Zee Entertainment",
    "pvr": "PVR INOX",
    "sun tv": "Sun TV Network",
    "mazdock": "Mazagon Dock Shipbuilders",
    "cochin shipyard": "Cochin Shipyard",
    "grse": "Garden Reach Shipbuilders",
    "beml": "BEML",
}
